name: pexels_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {freezed_annotation: ^2.1.0, http: ^0.13.5, json_annotation: ^4.6.0}
